"""empty message

Revision ID: 37308e70da2d
Revises: 
Create Date: 2023-10-10 20:13:49.300358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37308e70da2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debezium_config', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('ix_connections_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index('ix_connections_user_id', ['user_id'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('debezium_config')

    # ### end Alembic commands ###
