version: '3'
services:

  kafka-cluster:
    container_name: kafka-cluster
    image: landoop/fast-data-dev
    platform: linux/arm64
    environment:
      ADV_HOST: 127.0.0.1         
      RUNTESTS: 0
      CONNECTORS: debezium-postgres,s3
      AWS_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      SAMPLEDATA: 0
    ports:
      - 2181:2181                
      - 3030:3030                
      - 8081-8083:8081-8083
      - 9581-9585:9581-9585         
      - 9092:9092                   
    volumes:
      - ./target/plugin/:/connectors/
    links:
      - aws-s3

  postgres:
    image: debezium/postgres:13-alpine 
    platform: linux/arm64
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: circuitverse_development 
    networks:
      - metasync 

  spark:
    image: bitnami/spark 
    platform: linux/arm64
    environment:
      SPARK_MODE: master
    ports:
      - '8080:8080'
    networks:
      - metasync 

  spark-worker:
    image: bitnami/spark 
    platform: linux/arm64
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark:7077
    depends_on:
      - spark
    networks:
      - metasync 
 
  aws-s3:
    image: localstack/localstack
    platform: linux/arm64
    container_name: aws-s3
    environment:
      SERVICES: s3:5001
      HOSTNAME: aws-s3
      AWS_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID} 
      AWS_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY} 
    ports:
      - "5001:5001"

  cassandra_db:
    image: cassandra 
    platform: linux/arm64
    container_name: cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    networks:
      - metasync 

networks:
  metasync:
